version: "3"
services:
  auth-service:
    image: auth-service
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mynet
  crud-service:
    image: crud-service
    stdin_open: true
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    networks:
      - mynet
  rate-service:
    image: rate-service
    stdin_open: true
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - mynet         
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mynet 
networks:
  mynet:
    driver: bridge